silverstrike-master/silverstrike/urls.py
from django.urls import include, path
from django.views.generic import TemplateView

from rest_framework import routers
from rest_framework.authtoken import views as drf_views

from silverstrike import api
from silverstrike.rest import views as rest_views
from silverstrike.views import accounts as account_views
from silverstrike.views import budgets as budget_views
from silverstrike.views import categories as category_views
from silverstrike.views import charts as chart_views
from silverstrike.views import imports as import_views
from silverstrike.views import index as general_views
from silverstrike.views import recurrences as recurrence_views
from silverstrike.views import reports as report_views
from silverstrike.views import transactions as transaction_views


router = routers.DefaultRouter()
router.register(r'accounts', rest_views.AccountViewSet)
router.register(r'transactions', rest_views.TransactionViewSet)
router.register(r'categories', rest_views.CategoryViewSet)
router.register(r'recurrences', rest_views.RecurringTransactionsViewset)

urlpatterns = [
    path('', general_views.IndexView.as_view(), name='index'),
    path('profile/', general_views.ProfileView.as_view(), name='profile'),

    path('auth/', include('allauth.urls')),

    path('transactions/', transaction_views.TransactionIndex.as_view(), name='transactions'),
    path('transactions/<int:pk>/',
         transaction_views.TransactionDetailView.as_view(), name='transaction_detail'),
    path('transactions/<int:pk>/update/',
         transaction_views.TransactionUpdateView.as_view(), name='transaction_update'),
    path('transactions/<int:pk>/split/',
         transaction_views.SplitUpdate.as_view(), name='split_update'),
    path('transactions/<int:pk>/delete/',
         transaction_views.TransactionDeleteView.as_view(), name='transaction_delete'),
    path('transactions/create/transfer/',
         transaction_views.TransactionCreate.as_view(), {'type': 'transfer'}, name='transfer_new'),
    path('transactions/create/withdraw/',
         transaction_views.TransactionCreate.as_view(), {'type': 'withdraw'}, name='withdraw_new'),
    path('transactions/create/deposit/',
         transaction_views.TransactionCreate.as_view(), {'type': 'deposit'}, name='deposit_new'),
    path('transactions/create/split/',
         transaction_views.SplitCreate.as_view(), name='split_create'),

    path('accounts/<int:pk>/update/',
         account_views.AccountUpdate.as_view(), name='account_update'),
    path('accounts/<int:pk>/delete/',
         account_views.AccountDelete.as_view(), name='account_delete'),
    path('accounts/<int:pk>/all',
         account_views.AccountView.as_view(), {'period': 'all'}, name='account_detail_all'),
    path('accounts/<int:pk>/<dstart>/<dend>/',
         account_views.AccountView.as_view(), {'period': 'custom'}, name='account_detail'),
    path('accounts/<int:pk>/', account_views.AccountView.as_view(), {'period': 'month'},
         name='account_view'),
    path('accounts/<int:pk>/reconcile/',
         account_views.ReconcileView.as_view(), name='account_reconcile'),
    path('accounts/foreign/',
         account_views.ForeignAccountIndex.as_view(), name='foreign_accounts'),
    path('accounts/foreign/create/',
         account_views.ForeignAccountCreate.as_view(), name='foreign_account_new'),
    path('accounts/new/', account_views.AccountCreate.as_view(), name='account_new'),
    path('accounts/', account_views.AccountIndex.as_view(), name='accounts'),

    path('recurrences/',
         recurrence_views.RecurringTransactionIndex.as_view(), name='recurrences'),
    path('recurrences/create/',
         recurrence_views.RecurrenceCreateView.as_view(), name='recurrence_create'),
    path('recurrences/disabled/',
         recurrence_views.DisabledRecurrencesView.as_view(), name='disabled_recurrences'),
    path('recurrences/<int:pk>/', recurrence_views.RecurrenceDetailView.as_view(),
         name='recurrence_detail'),
    path('recurrences/<int:pk>/update/', recurrence_views.RecurrenceUpdateView.as_view(),
         name='recurrence_update'),
    path('recurrences/<int:pk>/delete/', recurrence_views.RecurrenceDeleteView.as_view(),
         name='recurrence_delete'),
    path('recurrences/<int:pk>/transaction/create/',
         recurrence_views.RecurrenceTransactionCreateView.as_view(),
         name='recurrence_transaction_create'),


    path('categories/', category_views.CategoryIndex.as_view(), name='categories'),
    path('categories/month/', category_views.CategoryByMonth.as_view(), name='category_by_month'),
    path('categories/inactive/', category_views.InactiveCategoriesView.as_view(),
         name='inactive_categories'),
    path('categories/month/<int:year>/<int:month>/', category_views.CategoryByMonth.as_view(),
         name='categories_month'),
    path('categories/assign/',
         category_views.assign_categories, name='category_assign'),
    path('categories/create/',
         category_views.CategoryCreateView.as_view(), name='category_create'),
    path('categories/<int:pk>/',
         category_views.CategoryDetailView.as_view(), name='category_detail'),
    path('categories/<int:pk>/<int:year>/<int:month>/',
         category_views.CategoryDetailView.as_view(), name='category_month'),
    path('categories/<int:pk>/delete/', category_views.CategoryDeleteView.as_view(),
         name='category_delete'),
    path('categories/<int:pk>/update/', category_views.CategoryUpdateView.as_view(),
         name='category_update'),

    path('budgets/', budget_views.BudgetIndex.as_view(), name='budgets'),
    path('budgets/<int:year>/<int:month>/',
         budget_views.BudgetIndex.as_view(), name='budget_month'),

    path('charts/', chart_views.ChartView.as_view(), name='charts'),

    path('reports/', report_views.ReportView.as_view(), name='reports'),
    path('reports/income-expense', report_views.IncomeExpenseReport.as_view(),
         name='income_expense_report'),

    path('api/accounts/<account_type>/', api.get_accounts, name='api_accounts'),
    path('api/balance/<dstart>/<dend>/', api.get_balances, name='api_balance'),
    path('api/non_dashboard_balance/<dstart>/<dend>/',
         api.get_non_dashboard_balances, name='api_non_dashboard_balance'),
    path('api/account/<int:account_id>/balance/<dstart>/<dend>/',
         api.get_account_balance, name='api_account_balance'),
    path('api/accounts_balance/<dstart>/<dend>/',
         api.get_accounts_balance, name='api_accounts_balance'),
    path('api/category_spending/<dstart>/<dend>/',
         api.category_spending, name='category_spending'),
    path('api/update_current_recurrences/',
         recurrence_views.ReccurrenceSetNextOccurence.as_view(),
         name='update_current_recurrences'),


    path('manifest.json', TemplateView.as_view(template_name='silverstrike/manifest.json'),
         name='manifest'),

    path('import/', import_views.ImportView.as_view(), name='import'),
    path('import/upload/', import_views.ImportUploadView.as_view(), name='import_upload'),
    path('import/process/<uuid:uuid>/',
         import_views.ImportProcessView.as_view(), name='import_process'),

    path('import/firefly/', import_views.ImportFireflyView.as_view(), name='import_firefly'),

    path('export/', import_views.ExportView.as_view(), name='export'),

    path('rest/account_names', rest_views.AccountNameView.as_view()),
    path('rest/recurrence_names', rest_views.RecurrenceNameView.as_view()),
    path('rest/accounts/personal', rest_views.PersonalAccountsView.as_view()),
    path('rest/accounts/foreign', rest_views.ForeignAccountsView.as_view()),
    path('rest/', include(router.urls)),
    path('api-token-auth/', drf_views.obtain_auth_token),
    path('api-auth/', include('rest_framework.urls', namespace='rest_framework')),

]

silverstrike-master/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('silverstrike.urls')),
]

silverstrike-master/silverstrike/models/account_type.py
from django.db import models
from django.utils.translation import gettext as _


class AccountType(models.IntegerChoices):
    PERSONAL = 1, _('Personal')
    FOREIGN = 2, _('Foreign')
    SYSTEM = 3, _('System')

silverstrike-master/silverstrike/views/charts.py
from datetime import date

from dateutil.relativedelta import relativedelta

from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import generic

from silverstrike.lib import last_day_of_month
from silverstrike.models import Transaction


class ChartView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'silverstrike/charts.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['menu'] = 'charts'
        context['today'] = date.today()
        context['minus_3_months'] = date.today() - relativedelta(months=3)
        context['minus_6_months'] = date.today() - relativedelta(months=6)
        context['minus_12_months'] = date.today() - relativedelta(years=1)
        context['all_time'] = date.today()
        if Transaction.objects.first():
            earliest_transaction = Transaction.objects.earliest('date')
            context['all_time'] = earliest_transaction.date - relativedelta(days=1)

        context['first_day_of_month'] = date.today().replace(day=1)
        context['last_day_of_month'] = last_day_of_month(date.today())
        return context

silverstrike-master/silverstrike/views/imports.py
import csv
import json
from datetime import date

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse, HttpResponseRedirect
from django.urls import reverse
from django.views import generic

from silverstrike import forms
from silverstrike import importers
from silverstrike import models


def _update_account(account, data):
    ibans = json.loads(account.import_ibans)
    names = json.loads(account.import_names)
    save = False
    if data.iban and data.iban not in ibans:
        ibans.append(data.iban)
        account.import_ibans = json.dumps(ibans)
        save = True
    if data.account and data.account not in names:
        names.append(data.account)
        account.import_names = json.dumps(names)
        save = True
    if save:
        account.save()


class ImportView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'silverstrike/import.html'


class ImportUploadView(LoginRequiredMixin, generic.edit.CreateView):
    model = models.ImportFile
    form_class = forms.ImportUploadForm
    template_name = 'silverstrike/import_upload.html'

    def form_valid(self, form):
        self.object = form.save()
        return HttpResponseRedirect(
            reverse('import_process', args=[self.object.pk]))


class ImportProcessView(LoginRequiredMixin, generic.TemplateView):
    template_name = 'silverstrike/import_configure_upload.html'

    def get_context_data(self, **kwargs):
        context = super(ImportProcessView, self).get_context_data(**kwargs)
        file = models.ImportFile.objects.get(uuid=self.kwargs['uuid'])
        importer = file.importer
        iban_accounts = dict()
        names = dict()
        for a in models.Account.objects.all():
            try:
                for iban in json.loads(a.import_ibans):
                    iban_accounts[iban] = a
            except json.decoder.JSONDecodeError:
                pass
            try:
                for name in json.loads(a.import_names):
                    if name in names and names[name] != a:
                        del names[name]
                        continue
                    names[name] = a
            except json.decoder.JSONDecodeError:
                pass
        context['data'] = importers.IMPORTERS[importer].import_transactions(file.file.path)
        max_date = date(1970, 1, 1)
        min_date = date(3000, 1, 1)
        for datum in context['data']:
            if datum.book_date < min_date:
                min_date = datum.book_date
            if datum.book_date > max_date:
                max_date = datum.book_date
            if datum.iban and datum.iban in iban_accounts:
                datum.suggested_account = iban_accounts[datum.iban]
            elif datum.account in names:
                datum.suggested_account = names[datum.account]

        # duplicate detection
        transactions = set()
        for t in models.Transaction.objects.date_range(min_date, max_date):
            if t.is_transfer:
                transactions.add('{}-{}-{}'.format(t.src_id, t.date, t.amount))
                transactions.add('{}-{}-{}'.format(t.dst_id, t.date, t.amount))
            elif t.is_deposit:
                transactions.add('{}-{}-{}'.format(t.src_id, t.date, t.amount))
            elif t.is_withdraw:
                transactions.add('{}-{}-{}'.format(t.dst_id, t.date, t.amount))
        for datum in context['data']:
            if hasattr(datum, 'suggested_account') and '{}-{}-{:.2f}'.format(
                    datum.suggested_account.id, datum.book_date, abs(datum.amount)) in transactions:
                datum.ignore = True

        context['recurrences'] = models.RecurringTransaction.objects.exclude(
            interval=models.RecurringTransaction.DISABLED).order_by('title')
        return context

    def post(self, request, *args, **kwargs):
        file = models.ImportFile.objects.get(uuid=self.kwargs['uuid'])
        importer = file.importer
        data = importers.IMPORTERS[importer].import_transactions(file.file.path)
        for i in range(len(data)):
            title = request.POST.get('title-{}'.format(i), '')
            account = request.POST.get('account-{}'.format(i), '')
            recurrence = int(request.POST.get('recurrence-{}'.format(i), '-1'))
            ignore = request.POST.get('ignore-{}'.format(i), '')
            book_date = data[i].book_date
            date = data[i].transaction_date
            if not (title and account) or ignore:
                continue
            amount = float(data[i].amount)
            if amount == 0:
                continue
            account, _ = models.Account.objects.get_or_create(
                name=account,
                defaults={'account_type': models.AccountType.FOREIGN})
            _update_account(account, data[i])
            if not account.iban and hasattr(data[i], 'iban'):
                account.iban = data[i].iban
                account.save()
            transaction = models.Transaction()
            if account.account_type == models.AccountType.PERSONAL:
                transaction.transaction_type = models.Transaction.TRANSFER
                if amount < 0:
                    transaction.src_id = file.account_id
                    transaction.dst = account
                else:
                    transaction.src = account
                    transaction.dst_id = file.account_id
            elif account.account_type == models.AccountType.FOREIGN:
                if amount < 0:
                    transaction.transaction_type = models.Transaction.WITHDRAW
                    transaction.src_id = file.account_id
                    transaction.dst = account
                else:
                    transaction.transaction_type = models.Transaction.DEPOSIT
                    transaction.dst_id = file.account_id
                    transaction.src = account
            transaction.title = title
            transaction.date = date
            transaction.amount = abs(amount)

            if recurrence > 0:
                transaction.recurrence_id = recurrence
            transaction.save()

            models.Split.objects.create(
                title=title,
                amount=amount,
                date=book_date,
                transaction=transaction,
                account_id=file.account_id,
                opposing_account=account
                )
            models.Split.objects.create(
                title=title,
                amount=-amount,
                date=date,
                transaction=transaction,
                account=account,
                opposing_account_id=file.account_id
                )
        return HttpResponseRedirect('/')


class ImportFireflyView(LoginRequiredMixin, generic.edit.CreateView):
    model = models.ImportFile
    fields = ['file']
    template_name = 'silverstrike/import_upload.html'

    def form_valid(self, form):
        self.object = form.save()
        importers.firefly.import_firefly(self.object.file.path)
        return HttpResponseRedirect(reverse('index'))


class ExportView(LoginRequiredMixin, generic.edit.FormView):
    template_name = 'silverstrike/export.html'
    form_class = forms.ExportForm

    def form_valid(self, form):
        response = HttpResponse(content_type='text/csv')

        splits = models.Split.objects.date_range(
            form.cleaned_data['start'], form.cleaned_data['end']).transfers_once()
        splits = splits.filter(account__in=form.cleaned_data['accounts'])
        csv_writer = csv.writer(response, delimiter=';')
        headers = [
            'account',
            'opposing_account',
            'date',
            'amount',
            'category'
            ]
        csv_writer.writerow(headers)
        for split in splits.values_list('account__name', 'opposing_account__name',
                                        'date', 'amount', 'category__name'):
            csv_writer.writerow(split)

        response['Content-Disposition'] = 'attachment; filename=export.csv'
        return response

silverstrike-master/silverstrike/templates/silverstrike/base.html
{% load static %}
{% load i18n %}
{% load account %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta content="width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no" name="viewport">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <link rel="icon" sizes="192x192" href="{% static 'silverstrike/img/android-chrome-192x192.png' %}">
    <link rel="icon" sizes="512x412" href="{% static 'silverstrike/img/android-chrome-512x512.png' %}">
    <link rel="shortcut icon" type="image/x-icon" sizes="32x32" href="{% static 'silverstrike/img/favicon-32x32.png' %}" />
    <link rel="shortcut icon" type="image/x-icon" sizes="16x16" href="{% static 'silverstrike/img/favicon-16x16.png' %}" />
    <link rel="manifest" href="{% url 'manifest' %}">
    {% block stylesheets %}
    {% endblock %}
    <link rel="stylesheet" href="{% static 'silverstrike/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/AdminLTE.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/css/skin-blue-light.min.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:300,400,600,700,300italic,400italic,600italic">
    <title>SilverStrike</title>
  </head>
  <body class="hold-transition skin-blue-light sidebar-mini">
    <div class="wrapper">
      <header class="main-header">
        <a href="/" class="logo">
          <!-- mini logo for sidebar mini 50x50 pixels -->
          <span class="logo-mini"><b>AgS</b></span>
          <!-- logo for regular state and mobile devices -->
          <span class="logo-lg"><b>Silver</b>strike</span>
        </a>
        <nav class="navbar navbar-static-top">
          <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
            <span class="sr-only">{% trans 'Toggle navigation' %}</span>
          </a>

          <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
              <li class="dropdown">
              <a href="#" class="dropdown-toggle" data-toggle="dropdown">{% trans 'New' %}</a>
              <ul class="dropdown-menu">
                <li class="header">
                  <a href="{% url 'withdraw_new' %}">{% trans 'New Withdrawal' %}</a>
                </li>
                <li>
                  <a href="{% url 'deposit_new' %}">{% trans 'New Deposit' %}</a>
                </li>
                <li>
                  <a href="{% url 'transfer_new' %}">{% trans 'New Transfer' %}</a>
                </li>
                <li>
                  <a href="{% url 'split_create' %}">{% trans 'New Split Transaction' %}</a>
                </li>
              </ul>
              </li>
              <li class="dropdown user user-menu">
                <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                  <i class="fa fa-user" aria-hidden="true"></i>
                  <span class="hidden-xs">{% user_display user %}</span>
                </a>
                <ul class="dropdown-menu">
                  <li class="user-header" id="navbar-user">
                    <p>
                    {% if request.user.first_name %}
                    {{ request.user.first_name }} {{ request.user.last_name }}
                    {% else %}
                    {% user_display user %}
                    {% endif %}
                    </p>
                  </li>
                  <li class="user-footer">
                    <div class="pull-left">
                      <a href="{% url 'profile' %}" class="btn btn-default btn-flat">{% trans 'Profile' %}</a>
                    </div>
                    <div class="pull-right">
                      <a href="{% url 'account_logout' %}" class="btn btn-default btn-flat">{% trans 'Sign out' %}</a>
                    </div>
                  </li>
                </ul>
              </li>
            </ul>
          </div>
        </nav>
      </header>
      <aside class="main-sidebar">
        <section class="sidebar">
          <ul class="sidebar-menu" data-widget="tree">
            <li class="header">{% trans 'MAIN NAVIGATION' %}</li>
            <li {% if menu == "home" %}class="active"{% endif %}>
              <a href="/">
                <i class="fa fa-home"></i> <span>{% trans 'Home' %}</span>
              </a>
            </li>
            <li{% if menu == "accounts" %} class="active"{% endif %}>
                <a href="{% url 'accounts' %}">
                  <i class="fa fa-bank fa-fw"></i>
                  <span>{% trans 'Accounts' %}</span>
                </a>
            </li>
            <li class="{% if menu == "transactions" %}active{% endif %}">
              <a href="{% url 'transactions' %}">
                <i class="fa fa-exchange fa-fw"></i>
                <span>{% trans 'Transactions' %}</span>
              </a>
            </li>
            <li{% if menu == "recurrences" %} class="active"{% endif %}>
              <a href="{% url 'recurrences' %}"><i class="fa fa-repeat"></i>
                <span>{% trans 'Recurrences' %}</span>
              </a>
            </li>
            <li{% if menu == "categories" %} class="active"{% endif%}>
              <a href="{% url 'category_by_month' %}">
                <i class="fa fa-tags" aria-hidden="true"></i>
                <span>{% trans 'Categories' %}</span>
              </a>
            </li>
            <li{% if menu == "budgets" %} class="active"{% endif%}>
              <a href="{% url 'budgets' %}">
                <i class="fa fa-book" aria-hidden="true"></i>
                <span>{% trans 'Budgets' %}</span>
              </a>
            </li>
            <li{% if menu == "reports" %} class="active"{% endif %}>
              <a href="{% url 'reports' %}">
                <i class="fa fa-line-chart" aria-hidden="true"></i>
                <span>{% trans 'Reports' %}</span>
              </a>
            </li>
            <li{% if menu == "charts" %} class="active"{% endif %}>
              <a href="{% url 'charts' %}">
                <i class="fa fa-pie-chart" aria-hidden="true"></i>
                <span>{% trans 'Charts' %}</span>
              </a>
            <li class="treeview{% if menu == "settings" %} active{% endif %}">
              <a href="#">
                <i class="fa fa-file-o fa-fw"></i>
                <span>{% trans 'Import &amp; Export' %}</span>
                <span class="pull-right-container">
                  <i class="fa fa-angle-left pull-right"></i>
                </span>
              </a>
              <ul class="treeview-menu">
                <li>
                  <a href="{% url 'import' %}"><i class="fa fa-download fa-fw"></i>{% trans 'Import' %}</a>
                </li>
                <li>
                  <a href="{% url 'export' %}"><i class="fa fa-upload fa-fw"></i>{% trans 'Export' %}</a>
                </li>
              </ul>
            </li>
          </ul>
        </section>
      </aside>
      <div class="content-wrapper">
          <div class="flash-message">
              {% for message in messages %}
              <div class="alert alert-dismissable">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
              </div>
              {% endfor %}
          </div>
        <section class="content-header">
          {% block content_header %}
          {% endblock %}
        </section>
        <section class="content">
          {% block content %}
          {% endblock %}
        </section>
      </div>
      <footer class="main-footer">
        <div class="pull-right hidden-xs">
          {% blocktrans with version="0.1.3" %}<b>Version</b> {{ version }}{% endblocktrans %}
        </div>
        <strong><a href="https://github.com/agstrike/silverstrike">SilverStrike</a></strong>
      </footer>
    </div>
    <script src="{% static 'silverstrike/js/jquery.min.js' %}"></script>
    <script src="{% static 'vendor/js/bootstrap.min.js' %}"></script>
    <script src="{% static 'vendor/js/adminlte.min.js' %}"></script>
    {% block scripts %}
    {% endblock %}
    <script>
        $(document).ready(function () {
            $('.sidebar-menu').tree()
            window.setTimeout(function() {
                $(".flash-message").fadeTo(500, 0).slideUp(500, function(){
                    $(this).remove();
                });
            }, 4000);
        })
    </script>
  </body>
</html>

silverstrike-master/silverstrike/templates/silverstrike/reports.html
{% extends 'silverstrike/base.html' %}
{% load i18n %}

{% block content %}
<div class="box">
    <div class="box-header">
        <h3 class="box-title">{% trans 'Reports' %}</h3>
    </div>
    <div class="box-body">
        <ul>
            <li><a href="{% url 'income_expense_report' %}">{% trans 'Income & Expense Report' %}</a></li>
        </ul>
    </div>
</div>
{% endblock %}

silverstrike-master/silverstrike/templates/silverstrike/transaction_split_form.html
{% extends 'silverstrike/base.html' %}
{% load i18n %}
{% load static %}
{% load widget_tweaks %}

{% block content_header %}
<h1>Transactions
  <small>
    {% if object %}
    {% blocktrans with object_name=object.title %}Edit {{ object.title }}{% endblocktrans %}
    {% else %}
    {% blocktrans %}Add new {{ submenu }}{% endblocktrans %}
    {% endif %}
  </small>
</h1>
<ol class="breadcrumb">
  <li><a href="/">{% trans 'Home' %}</a></li>
  <li><a href="{% url 'transactions' %}">{% trans 'Transactions' %}</a></li>
  {% if object %}
  <li><a href="{{ object.get_absolute_url }}">{{ object }}</a></li>
  <li class="active">{% trans 'Edit' %}</li>
  {% else %}
  <li class="active">{% trans 'Create' %}</li>
  {% endif %}
</ol>
{% endblock %}

{% block content %}
<div class="box">
  <div class="box-header with-border">
    <h3 class="box-title">{% trans 'Transaction Details' %}</h3>
  </div>
  <div class="box-body">
    <form method="post" class="form-horizontal">
      {% csrf_token %}
      {% for field in form %}
        <div class="form-group{% if field.errors %} has-error{% endif %}">
          <label class="col-sm-2 control-label" for="{{ field.id_for_label }}">{{ field.label }}
          </label>
          <div class="col-sm-8">
            {% if field|widget_type == 'dateinput' %}
            {{ field|add_class:"form-control dateinput" }}
            {% else %}
            {{ field|add_class:"form-control" }}
            {% endif %}
            {% for error in field.errors %}
            <span class="help-block">{{ error }}</span>
            {% endfor %}
          </div>
        </div>
      {% endfor %}
      <br>
      {% for error in form.non_field_errors %}
      {{ error }}
      {% endfor %}
      {{ formset.management_form }}
      <table id="formset" class="table">
        {% for split in formset %}
        {% if forloop.first %}
        <tr>
          {% for field in split.visible_fields %}
          <th>{{ field.label }}</th>
          {% endfor %}
        </tr>
        {% endif %}
        <tr>
          {% for field in split.visible_fields %}
          {% if field|widget_type == 'checkboxinput' %}
          <td class="text-center">{{ field }}</td>
          {% else %}
          <td class="form-group{% if field.errors %} has-error{% endif %}">
            {% if field|widget_type == 'dateinput' %}
            {{ field|add_class:"form-control dateinput" }}
            {% else %}
            {{ field|add_class:"form-control" }}
            {% endif %}
          </td>
          {% endif %}
          {% endfor %}
          {% for field in split.hidden_fields %}
          {{ field }}
          {% endfor %}
        </tr>
        {% if split.errors %}
        <tr>
          {% for error in split.errors %}
          <span class="help-block">{{ error }}</span>
          {% endfor %}
        </tr>
        {% endif %}
        {% endfor %}
      </table>
      <button type="submit" class="btn btn-primary col-md-offset-2">{% if object %}{% trans 'Update' %}{% else %}{% trans 'Create' %}{% endif %}</button>
      <a id="add-split" class="btn btn-info">{% trans 'Add Split' %}</a>
    </form>
  </div>
</div>
{% endblock %}

{% block stylesheets %}
<link rel="stylesheet" href="{% static 'vendor/css/bootstrap-datepicker.min.css' %}">
{% endblock %}

{% block scripts %}
<script src="{% static 'vendor/js/bootstrap-datepicker.min.js' %}"></script>
<script>
function cloneMore(selector) {
    var newElement = $(selector).clone(true);
    var total = $('#id_splits-TOTAL_FORMS').val();
    newElement.find(':input').each(function() {
        var name = $(this).attr('name').replace('-' + (total - 1) + '-','-' + total + '-');
        var id = 'id_' + name;
        $(this).attr({'name': name, 'id': id}).val('').removeAttr('checked');
    });
    newElement.find('.dateinput').each(function() {
        $(this).attr("id", "").removeData().off();
        $(this).find('.add-on').removeData().off();
        $(this).find('input').removeData().off();
        $(this).datepicker({
            autoclose: true,
            format: 'yyyy-mm-dd',
            disableTouchKeyboard: true
          });
    });
    newElement.find('label').each(function() {
        var newFor = $(this).attr('for').replace('-' + (total - 1) + '-','-' + total + '-');
        $(this).attr('for', newFor);
    });
    $('#id_splits-TOTAL_FORMS').val(++total);
    $(selector).after(newElement);
}
$(function() {
  $('.dateinput').datepicker({
    autoclose: true,
    format: 'yyyy-mm-dd',
    disableTouchKeyboard: true
  });
  $('.dateinput').attr('autocomplete', 'off');
  $('#add-split').click(function() {
    cloneMore('#formset tr:last');
  });
});
</script>
{% endblock %}